"""add colume gold

Revision ID: 3e6b95312378
Revises: f0a0f9e08dcc
Create Date: 2021-12-05 16:01:05.653529+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6b95312378'
down_revision = 'f0a0f9e08dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('gold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'gold')
    # ### end Alembic commands ###
