"""delete colume gold

Revision ID: f0a0f9e08dcc
Revises: c6cfeb7867bd
Create Date: 2021-12-05 15:58:30.267247+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a0f9e08dcc'
down_revision = 'c6cfeb7867bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'gold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
